### PR TITLE
Set Day 2 as a link instead of just text

### LINKED ISSUE #378: [doc] Issue in "Upgrade Steps"
Upgrade Steps:

https://documentation.suse.com/suse-edge/3.0/html/edge/id-release-notes.html#id-upgrade-steps

A link here would be nice.

### PR DESCRIPTION
**Pull request by e-minguez**
Fixes #378

### CODE REVIEW

**Comment by e-minguez** [comment]
@ranjinimn could you please help me with this? I'm not sure if that's the proper way to link a section directly.

**Comment by e-minguez** [comment]
Yep, the build failed as:
```
error: IDREF "day2" without matching ID
```

I only see a proper header on the first day 2 doc https://github.com/suse-edge/suse-edge.github.io/blob/main/asciidoc/day2/mgmt-cluster.adoc?plain=1#L1

Shall we use this then?

**Comment by ipetrov117** [comment]
> Yep, the build failed as:
> 
> ```
> error: IDREF "day2" without matching ID
> ```
> 
> I only see a proper header on the first day 2 doc https://github.com/suse-edge/suse-edge.github.io/blob/main/asciidoc/day2/mgmt-cluster.adoc?plain=1#L1
> 
> Shall we use this then?

IMO referring to the mgmt-cluster only is not desirable, maybe it would be better to add a link [here](https://github.com/suse-edge/suse-edge.github.io/blob/main/asciidoc/edge-book/edge.adoc?plain=1#L112) and refer that link in the RN/Upgrade Steps?

**Review by ranjinimn — APPROVED** [review]
@e-minguez It looks good.

**Review by hardys — APPROVED** [review]

**Pull request merged**
