### PR TITLE
Fix typos and wording

### PR DESCRIPTION
**Pull request by fdegir**
This commit
* Fixes typos, wording
* Removes trailing whitespaces
* Replaces the word bare-metal with bare metal for consistency
* Updates other minor issues

### CODE REVIEW

**Comment by fdegir** [comment]
As this PR touches lots of files, please let me know if it is preferred to send separate PRs organized accordingly such as sending PR per chapter (e.g., components, guides, product) for ease of review.

**Review by hardys — APPROVED** [review]
lgtm, thanks!

**Comment by hardys** [comment]
> As this PR touches lots of files, please let me know if it is preferred to send separate PRs organized accordingly such as sending PR per chapter (e.g., components, guides, product) for ease of review.

If this were making changes to content then yes I think multiple PRs would make sense, but given that it's cosmetic/cleanups which are similar in each file IMO the current approach is fine.

**Review by agracey — APPROVED** [review]
Thank you!

**Pull request merged**
