### PR TITLE
Alignment with Rancher Turtles

### PR DESCRIPTION
**Pull request by hardys**
This aligns with the recently added suse-edge charts which enable management of CAPI dependencies via Rancher Turtles

Depends On:
https://github.com/suse-edge/charts/pull/150 (merged) and https://github.com/suse-edge/charts/pull/154

### CODE REVIEW

**Comment by hardys** [comment]
Also see https://github.com/suse-edge/atip/pull/7

**Review by alknopfler — APPROVED** [review]
LGTM! Thanks Steven

**Comment by hardys** [comment]
One thing to note is this currently refers to charts we've not yet published via registry.suse.com - I think we'll have that issue in other places, but if preferred I can update this to reference the suse-edge/charts upstream charts instead as a temporary measure

**Review by Kristian-ZH — APPROVED** [review]
lgtm

**Pull request merged**
