### PR TITLE
Align bare-metal references and update architecture diagram

### PR DESCRIPTION
**Pull request by hardys**
Improve consistency of non-API usage of this term, and update the architecture diagram to include the SLEMicro layer on the Management Stack

Fixes: #395
Fixes: #427

### CODE REVIEW

**Review by atanasdinov — APPROVED** [review]
I'm wondering whether the new size of the image would be displayed properly but I guess we can figure it out once we merge this.

**Comment by hardys** [comment]
> I'm wondering whether the new size of the image would be displayed properly but I guess we can figure it out once we merge this.

Hmm good point - I didn't spot the size difference, but I did build locally and the preview looked OK to me, so lets merge and if there are any issues I'll push a follow-up with a larger image.

**Comment by hardys** [comment]
@atanasdinov The published https://suse-edge.github.io/atip-architecture.html looks OK to me but let me know if you spot any issues, thanks!

**Review by ranjinimn — COMMENTED** [review]
LGTM

**Pull request merged**
